---
sidebar: sidebar 
permalink: task-create-azure-connector-user-consent-snapcenter-service.html 
keywords: azure, connector, cloud central, snapcenter service, user consent, tenant admin, create connector, enable, disable, azure marketplace 
summary: 在 Azure 中为 SnapCenter 服务创建连接器。 
---
= 在 Azure 中为 SnapCenter 服务创建连接器
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
客户管理员应先部署 Connector ，然后才能使用 Cloud Manager 功能。借助此连接器， Cloud Manager 可以管理公有云环境中的资源和流程。

默认情况下，您可以从 Azure Marketplace 在 Azure 中创建 Connector 。执行步骤至时 https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-launching-azure-mktp.html["从 Azure Marketplace 创建连接器"]，您应记住以下几点：

* 无论在何处指定适用于 Cloud Volumes ONTAP 的 Cloud Manager ， SnapCenter 服务都可以使用这种方式。
* 对于 Cloud Manager Name ，请指定您的 Connector VM 名称以更好地进行标识。此名称将在 Cloud Manager UI 中显示为连接器名称。
* 如果您在未配置公有 IP 的情况下配置了连接器或配置了防火墙，则应使用跳转主机连接到连接器计算机。


如果您有 https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-user-consent?tabs=azure-portal#user-consent-settings["用户同意"^] 在 Azure Active Directory 中启用，或者如果租户管理员可以提供同意，您可以从 Cloud Manager UI 创建 Connector 。



== 已启用用户同意

如果在 Azure Active Directory 中启用了用户同意， https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["从 Cloud Manager 创建 Connector"]。



== 已禁用用户同意

. 执行以下操作之一：
+
** 如果在 Active Directory 中配置了管理员同意工作流，则应执行此操作 https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/configure-admin-consent-workflow#how-users-request-admin-consent["请求管理员同意"^]。
** 如果未配置管理员同意工作流，您应：
+
... https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent#construct-the-url-for-granting-tenant-wide-admin-consent["构建用于授予租户范围管理员同意的 URL"^]。
+

NOTE: 将客户端 ID 指定为 _989efff4-9a9e-46fa-9f17-de39e15714f9_ 。这是在 Cloud Manager 向导中命名的 Cloud Manager Azure 应用程序 ID 。

... 请租户管理员在浏览器中运行此 URL ，并征得其同意。
+
管理员可以忽略显示的错误





. https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-creating-connectors-azure.html["从 Cloud Manager 创建 Connector"]。



IMPORTANT: 要连接到计算机，需要用户名和密码或在创建 Connector 时提供的密钥
